/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein
 * is confidential and proprietary to MediaTek Inc. and/or its licensors.
 * Without the prior written permission of MediaTek inc. and/or its licensors,
 * any reproduction, modification, use or disclosure of MediaTek Software,
 * and information contained herein, in whole or in part, shall be strictly prohibited.
 */
/* MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON
 * AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
 * NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
 * SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
 * SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES TO LOOK ONLY TO SUCH
 * THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES
 * THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES
 * CONTAINED IN MEDIATEK SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK
 * SOFTWARE RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND
 * CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
 * AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
 * OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY RECEIVER TO
 * MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek Software")
 * have been modified by MediaTek Inc. All revisions are subject to any receiver's
 * applicable license agreements with MediaTek Inc.
 */

#ifndef __KERNEL_RTPM_PRIO__
#define __KERNEL_RTPM_PRIO__

#define RTPM_PRIO_SWLOCKUP		99
#define RTPM_PRIO_AED			99
#define RTPM_PRIO_WDT			99
#define RTPM_PRIO_PLAYBACK_THREAD	95
#define RTPM_PRIO_SCRN_UPDATE		94
#define RTPM_PRIO_CAMERA_PREVIEW	91
#define RTPM_PRIO_CAMERA_COMPRESS	90
#define RTPM_PRIO_FB_THREAD	 	87
#define RTPM_PRIO_3D_LAYER		86
#define RTPM_PRIO_SURFACEFLINGER	84
#define RTPM_PRIO_SURFACE_OUT		80
#define RTPM_PRIO_OMX_VIDEO		75

#define RTPM_PRIO_RECORD_THREAD		44
#define RTPM_PRIO_AUDIO_IN		43
#define RTPM_PRIO_PV_AUTHOR		42
#define RTPM_PRIO_PV_MP4COMPOSER	41

#define RTPM_PRIO_AUDIO_COMMAND		69
#define RTPM_PRIO_AUDIO_OUT		64
#define RTPM_PRIO_AUDIO_CCCI_THREAD	62
#define RTPM_PRIO_VORBIS_DECODE		92

#define RTPM_PRIO_MIDI_FILE		30
#define RTPM_PRIO_PV_MNTMON		9	
#define RTPM_PRIO_PV_METARETR		8
#define RTPM_PRIO_TPD			4
#define RTPM_PRIO_KSDIOIRQ		1
#define RTPM_PRIO_AUDIOTRACK_THREAD	1

#define RTPM_PRIO_NUM	26

#endif
